name: windows-bundler

on:
  pull_request:

  push:
    branches:
      - master
      - 3.3

concurrency:
  group: ci-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  windows_bundler:
    name: Bundler on Windows (${{ matrix.ruby.name }})

    runs-on: windows-2022

    env:
      RGV: ..

    strategy:
      fail-fast: false
      matrix:
        ruby:
          - { name: ruby-3.1, value: 3.1.2 }

    steps:
      - uses: actions/checkout@v3
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby.value }}
          bundler: none
      - name: Install dependencies
        run: |
          bin/rake spec:parallel_deps
        working-directory: ./bundler
        shell: bash
      - name: Run specs
        run: |
          bin/rspec spec/install/global_cache_spec.rb:44
        working-directory: ./bundler
        shell: bash
